models/Stock.php
<?php

namespace app\models;

use Yii;
use yii\base\Exception;
use app\models\StockPrice;
use app\models\StockRoi;
use app\components\StockChartOwnerBehavior;

/**
 * This is the model class for table "stock".
 *
 * @property string $id
 * @property string $symbol_id
 * @property string $sector_id
 * @property string $industry_id
 * @property string $exchange_id
 * @property string $symbol
 * @property string $market_cap
 * @property integer $ipo_year
 * @property string $summary_quote
 * @property string $created_at
 * @property string $updated_at
 * @property string $stock_price
 * @property integet $volume
 *
 * @property Sector $sector
 * @property Industry $industry
 * @property Exchange $exchange
 * @property StockPrice[] $stockPrices
 */
class Stock extends \yii\db\ActiveRecord
{

    public $charts;
    private $lastRoiModel;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'stock';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sector_id', 'industry_id', 'exchange_id', 'symbol', 'market_cap', 'created_at', 'updated_at'], 'required'],
            [['sector_id', 'industry_id', 'exchange_id', 'ipo_year'], 'integer'],
            [['market_cap', 'stock_price', 'volume'], 'number'],
            [['created_at', 'updated_at'], 'safe'],
            [['summary_quote'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'sector_id' => Yii::t('app', 'Sector ID'),
            'industry_id' => Yii::t('app', 'Industry ID'),
            'exchange_id' => Yii::t('app', 'Exchange ID'),
            'symbol' => Yii::t('app', 'Symbol'),
            'market_cap' => Yii::t('app', 'Market Cap'),
            'ipo_year' => Yii::t('app', 'Ipo Year'),
            'summary_quote' => Yii::t('app', 'Summary Quote'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'stock_price' => Yii::t('app', 'Stock Price'),
            'volume' => Yii::t('app', 'Volume'),
        ];
    }
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => StockChartOwnerBehavior::className(), 
                'chartsListOwnerPropertyName' => 'charts'
            ]
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSector()
    {
        return $this->hasOne(Sector::className(), ['id' => 'sector_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIndustry()
    {
        return $this->hasOne(Industry::className(), ['id' => 'industry_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getExchange()
    {
        return $this->hasOne(Exchange::className(), ['id' => 'exchange_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStockPrices()
    {
        return $this->hasMany(StockPrice::className(), ['stock_id' => 'id']);
    }

    /**
     * @return StockRoi
     */
    public function getLastRoi()
    {
        if (!is_null($this->lastRoiModel)) {
            return $this->lastRoiModel;
        }

        $lastRoiModel = StockRoi::find()
            ->where(['stock_id' => $this->id])
            ->orderBy('date DESC')
            ->one();

        if (!$lastRoiModel) {
            $lastRoiModel = new StockRoi();
        }    

        return $this->lastRoiModel = $lastRoiModel;
    }

    /**
     * Get average roi for the last 12 months
     */
    public function getAverageRoi()
    {
        $currentDt = new \DateTime();
        $yearAgoDt = clone $currentDt;
        $yearAgoDt->sub(\DateInterval::createFromDateString('+1 years'));

        $oneMonthInterval = \DateInterval::createFromDateString('+1 months');

        $roiSum = 0;
        $months = 0;
        $dates = [];
        do {
            $dates[] = $currentDt->format('Y-m-01');
            $currentDt->sub($oneMonthInterval);
        } while ($currentDt > $yearAgoDt);

        $stockRoiModels = StockRoi::find()
            ->where(['stock_id' => $this->id])
            ->andWhere(['date' => $dates])
            ->all();

        foreach ($stockRoiModels as $item) {
            $roiSum += $item->roi_1m;
            $months++;
        } 

        return $roiSum / $months;
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\BadRequestHttpException;
use yii\filters\VerbFilter;
use app\models\Stock;
use app\models\StockPrice;
use app\models\SearchForm;
use app\models\Industry;
use app\models\StockHistory;

/**
 * Class SiteController
 *
 * @package app\controllers
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'index' => ['get', 'post'],
                    'stock' => ['get'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Get page title based on a search form params
     *
     * @param SearchForm $searchForm
     */
    private function getTitleBasedOnSearchForm(SearchForm $searchForm)
    {
        $title = $searchForm->roi_max ? Yii::t('app', 'Max') : Yii::t('app', 'Min');
    
        $map = [
            'roi_1m' => 'ROI1M',
            'roi_3m' => 'ROI3M',
            'roi_6m' => 'ROI6M',
            'roi_1' => 'ROI1',
            'roi_2' => 'ROI2',
            'roi_3' => 'ROI3',
        ];
        $items = [];
        foreach ($map as $property => $name) {
            if (!isset($searchForm->{$property})) {
                continue;
            }
            $value = (int)$searchForm->{$property};
            if ($value == 0) {
                continue;
            }
            $items[] = $name . ': ' . $value . '%';
        }

        return count($items) > 0 ? ($title .= ' ' . implode(' ', $items)) : null;
    }

    /**
     * Default action
     */
    public function actionIndex()
    {
        $searchForm = new SearchForm();
        $searchForm->load(Yii::$app->request->get());
        $searchForm->validate();   


        $dateTo = $searchForm->date_to ? new \DateTime($searchForm->date_to) : new \DateTime();
        $dateToMinusThreeYears = clone $dateTo;
        $dateToMinusThreeYears->add(\DateInterval::createFromDateString('-3 years'));

        // Get ROIs list and stock ids list
        $roiModels = $searchForm->dataProvider->getModels();
        $stockIds = [];
        foreach ($roiModels as $roiModel) {
            $stockIds[] = $roiModel->stock_id;
        }

        // Get stocks list
        $stockModels = Stock::find()
            ->where(['id' => $stockIds])
            ->all();
        unset($stockIds);    
        $industryIds = [];
        $prepared = [];
        foreach ($stockModels as $stockModel) {
            foreach ($roiModels as $roiModel) {
                if ($roiModel->stock_id == $stockModel->id) {
                    $prepared[$roiModel->id] = $stockModel;
                }                                
            }
            $industryIds[] = $stockModel->industry_id;
        }
        $stockModels = $prepared;
        unset($prepared);

        // Get industries list
        $industryIds = array_unique($industryIds);
        $industryModels = Industry::find()
            ->where(['id' => $industryIds])
            ->all();
        unset($industryIds);   
        $prepared = []; 
        foreach ($stockModels as $stockModel) {
            foreach ($industryModels as $industryModel) {
                if ($stockModel->industry_id == $industryModel->id) {
                    $prepared[$stockModel->id] = $industryModel;
                }
            }
        }
        $industryModels = $prepared;
        unset($prepared);

        return $this->render(
            'index', 
            [
                'title' => $this->getTitleBasedOnSearchForm($searchForm),
                'searchForm' => $searchForm, 
                'sortFieldName' => $this->getSortFieldName(),
                'sortPeriod' => $this->getSortPeriod(),
                'sortDirection' => $this->getSortDirection(),
                'dateTo' => $dateTo,
                'dateToMinusThreeYears' => $dateToMinusThreeYears,
                'showCharts' => $dateTo->diff(new \DateTime())->m == 0 || $searchForm->go_direction, 
                'stockModels' => $stockModels,
                'industryModels' => $industryModels,
                'roiPeriods' => [
                    'roi_1' => $this->getSortPeriod('roi_1'),
                    'roi_2' => $this->getSortPeriod('roi_2'),
                    'roi_3' => $this->getSortPeriod('roi_3'),
                    'roi_1m' => $this->getSortPeriod('roi_1m'),
                    'roi_3m' => $this->getSortPeriod('roi_3m'),
                    'roi_6m' => $this->getSortPeriod('roi_6m'),
                    'roi_3years' => $this->getSortPeriod('roi_3years'),
                ],
            ]
        );
    }

    public function actionStock()
    {

        $stockId = Yii::$app->request->get('stock_id', null);
        if (is_null($stockId)) {
            throw new BadRequestHttpException(Yii::t('app', 'Empty stock id'));
        }
        if (!is_numeric($stockId)) {
            throw new BadRequestHttpException(Yii::t('app', 'Stock id is not numeric'));
        }

        return $this->render(
            'stock',
            [
                'stockHistory' => new StockHistory($stockId),
            ]
        );
    }

    /**
     * 
     * @return string
     */
    private function getSortDirection()
    {
        $sort = Yii::$app->request->get('sort');
        return ($sort{0} === '-' ? 'desc' : 'asc');
    }

    /**
     * Get sort period
     *
     * @param string $sort
     * @return array|null
     */
    private function getSortPeriod($sort = null)
    {
        if ($sort === null) {
            $sort = Yii::$app->request->get('sort');
        }
        if (!$sort) {
            return null;
        }

        $field = str_replace('-', null, $sort);

        $beginDt = new \DateTime('first day of this month');
        $endDt = clone $beginDt;

        switch ($field) {
            case 'roi_1':
                $beginDt->add(\DateInterval::createFromDateString('-1 years'));
                break;
            case 'roi_2':
                $beginDt->add(\DateInterval::createFromDateString('-2 years'));
                $endDt->add(\DateInterval::createFromDateString('-1 years'));
                break;
            case 'roi_3':
                $beginDt->add(\DateInterval::createFromDateString('-3 years'));
                $endDt->add(\DateInterval::createFromDateString('-2 years'));
                break;
            case 'roi_1m':
                $beginDt->add(\DateInterval::createFromDateString('-1 months'));
                break;    
            case 'roi_3m':
                $beginDt->add(\DateInterval::createFromDateString('-3 months'));
                break;
            case 'roi_6m':
                $beginDt->add(\DateInterval::createFromDateString('-6 months'));
                break;
            case 'roi_3years':
                $beginDt->add(\DateInterval::createFromDateString('-3 years'));
                break;
            case 'eps':
                break;
            case 'roi_best':
            case 'roi_worst':
                $beginDt->add(\DateInterval::createFromDateString('-1 years'));
                break;
            default:
                throw new BadRequestHttpException('Unknown sort field: ' . $field);                 
        }

        return [$beginDt, $endDt];
    }

    /**
     * Get sort field name
     *
     * @return string|null
     */
    private function getSortFieldName()
    {
        $sort = Yii::$app->request->get('sort', null);
        if (!$sort) {
            return null;
        }
        $field = str_replace(['-', '_'], null, $sort);
        $field = str_replace('years', 'Y', $field);
        return strtoupper($field);
    }

}

views/site/chart_cell.php
<?php
/** @var $stock app\models\Stock */
/** @var $roi app\models\StockRoi */
/** @var $index int **/

use app\models\StockChart;
?>
<?php if (isset($stock->charts[StockChart::$types['TYPE_YEARLY_3']])): ?>
<a class="anchor-chart-modal-opener"
	id="chart-modal-opener-<?= $index ?>" 
	data-index="<?= $index ?>"
	data-symbol="<?= $stock->symbol ?>" 
	data-roi-one-month="<?= round($roi->roi_1m, 2) ?>"
	data-roi-three-months="<?= round($roi->roi_3m, 2) ?>"
	data-roi-six-months="<?= round($roi->roi_6m, 2) ?>"
	data-roi-one="<?= round($roi->roi_1, 2) ?>" 
	data-roi-two="<?= round($roi->roi_2, 2) ?>"
	data-roi-three="<?= round($roi->roi_3, 2) ?>"  
	data-roi-best="<?= round($roi->roi_best, 2) ?>"
	data-roi-worst="<?= round($roi->roi_worst, 2) ?>"
	href="<?= $stock->charts[StockChart::$types['TYPE_YEARLY_3']]->getChartFileUrl() ?>">
    <img src="<?= $stock->charts[StockChart::$types['TYPE_YEARLY_3']]->getChartThumbnailUrl(200, 100) ?>" alt="" />
</a>    
<?php else: ?>
(<?= Yii::t('app', 'not set') ?>)
<?php endif; ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/stock.php
<?php
/** @var $stockHistory \app\models\StockHistory */

use yii\helpers\Url;
use app\models\StockChart;

$this->registerJsFile('@web/js/chart-anchors-stock.js', ['depends' => \yii\web\JqueryAsset::className()]);
$this->params['breadcrumbs'] = [
	[
		'label' => Yii::t('app', $stockHistory->stock->symbol)
	]
];
$this->title = 'Stock Informer: ' . Yii::t('app', '{symbol} details', ['symbol' => $stockHistory->stock->symbol]);
?>
<div class="site-index">
	<div class="body-content">
		<h1><?= $stockHistory->stock->symbol ?></h1>
		<div class="row">
			<div class="col-xs-3">
				<?php 
				echo \yii\grid\GridView::widget(
					[
						'dataProvider' => $stockHistory->dataProvider, 
						'columns' => [
							'date', 
							[
								'class' => \yii\grid\DataColumn::className(),
								'attribute' => 'price',
								'value' => function ($model) {
									return Yii::$app->formatter->asDecimal($model['price'], 2);
								},
							], 
							[
								'class' => \yii\grid\DataColumn::className(),
								'attribute' => 'roi_1m',
								'content' => function ($model) {
									$html = '<span class="value-' . ($model['roi_1m'] >= 100 ? 'green' : 'red') . '">';
									$html .= Yii::$app->formatter->asDecimal($model['roi_1m'], 2) . '%';
									return $html .= '</span>';
								},
							],
						],
						'pager' => [
							'maxButtonCount' => 6
						],
					]
				); 
				?>
			</div>
			<div class="col-xs-9">
				<h2><?= Yii::t('app', 'Information') ?></h2>
				<div class="list-group">

					<li class="list-group-item">
						<b><?= Yii::t('app', 'AVG ROI') ?>/<?= Yii::t('app', 'Month') ?>:</b> 
						<?= Yii::$app->formatter->asDecimal($stockHistory->stock->averageRoi, 2) ?>%
					</li>
					<?php
					$valuesToShow = [
						'eps' => 'EPS',
						'roi_best' => 'BestROI',
						'roi_worst' => 'WorstROI',
						'roi_1m' => 'ROI1M',
						'roi_3m' => 'ROI3M',
						'roi_6m' => 'ROI6M',
						'roi_1' => 'ROI1',
					];
					?>
					<?php foreach ($valuesToShow as $property => $label): ?>
						<?php if ($stockHistory->stock->lastRoi->{$property}): ?>
							<div class="list-group-item">
								<b><?= Yii::t('app', $label) ?>:</b>
								<?= Yii::$app->formatter->asDecimal($stockHistory->stock->lastRoi->{$property}, 2) ?><?php if (strpos($property, 'roi') !== false): ?>%<?php endif; ?>
							</div>
						<?php endif; ?>
					<?php endforeach; ?>

					<a class="list-group-item list-group-item-info" 
						href="http://elite.finviz.com/quote.ashx?t=<?= $stockHistory->stock->symbol ?>&ty=p&ta=0&p=d" 
						target="_blank"><?= Yii::t('app', 'Performance') ?></a>

					<a class="list-group-item list-group-item-info"
						href="http://www.google.com/finance?q=<?= $stockHistory->stock->symbol ?>"
						target="_blank"><?= Yii::t('app', 'Google Finance') ?></a>

					<?php
						$currentDt = new \DateTime();
						$threeYearsAgoDt = clone $currentDt;
						$threeYearsAgoDt->sub(DateInterval::createFromDateString('+3 years'));
					?>
					<a class="list-group-item list-group-item-info"
						href='http://finance.yahoo.com/echarts?s=<?= $stockHistory->stock->symbol ?>+Interactive#{"customRangeStart":<?= $threeYearsAgoDt->format('U') ?>,"customRangeEnd":<?= $currentDt->format('U') ?>,"range":"custom","allowChartStacking":true}'
						target="_blank">Yahoo</a>

				</div>

				<h2><?= Yii::t('app', 'Charts') ?></h2>
				<?php 
					$chartTypes = [
						'TYPE_DAILY', 'TYPE_WEEKLY'
					];
				?>
				<?php foreach ($chartTypes as $type): ?>
					<?php if (isset($stockHistory->stock->charts[StockChart::$types[$type]])): ?>
						<?php 
							$label = str_replace('TYPE_', null, $type);
							$label = ucfirst(strtolower($label));
						?>
						<?php $chart = $stockHistory->stock->charts[StockChart::$types[$type]]; ?>
						<div class="thumbnail">
							<a class="chart-modal-opener" data-symbol="<?= $stockHistory->stock->symbol ?>" data-type="<?= $label ?>" href="<?= $chart->getChartFileUrl() ?>" target="_blank">
								<img src="<?= $chart->getChartThumbnailUrl(800, 700) ?>" alt="<?= Yii::t('app', $label) ?>">
							</a>
							<div class="caption">
								<h3><?= Yii::t('app', $label) ?></h3>
							</div>
						</div>
					<?php endif; ?>
				<?php endforeach; ?>
			</div>	
		</div>			
	</div>
</div>
<?php 
	\yii\bootstrap\Modal::begin(
		[
			'id' => 'modal-chart',
			'size' => \yii\bootstrap\Modal::SIZE_LARGE,
			'header' => '<h4></h4>',
			'options' => [
				'class' => 'modal-centered'
			],
		]
	); 
?>
<?php \yii\bootstrap\Modal::end(); ?>